#pragma once
#include <ScaleformUILib\Scaleform\common.h>
#include "GTAVInfrastructure\SHV\natives.h"



class RankBarHandler
{
private:
	const int HUD_COMPONENT_ID = 19;


public:
	HudColour Color = HudColour::HUD_COLOUR_FREEMODE;

	RankBarHandler() { }

	void Load()
	{
		int timeout = 1000;

		int start = MISC::GET_GAME_TIMER();
		GRAPHICS::REQUEST_SCALEFORM_SCRIPT_HUD_MOVIE(HUD_COMPONENT_ID);
		while (!GRAPHICS::HAS_SCALEFORM_SCRIPT_HUD_MOVIE_LOADED(HUD_COMPONENT_ID) && MISC::GET_GAME_TIMER() - start < timeout)
		{
			WAIT(0);
		}
	}
	void SetScores(int limitStart, int limitEnd, int previousValue, int currentValue, int currentRank)
	{
		Load();
		// Color has to be set else it will be white by default
		GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(HUD_COMPONENT_ID, "SET_COLOUR");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT((int)Color);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();

		// this will set an update the score
		GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(HUD_COMPONENT_ID, "SET_RANK_SCORES");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(limitStart);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(limitEnd);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(previousValue);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(currentValue);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(currentRank);
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(100);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
	}

	void Remove()
	{
		if (GRAPHICS::HAS_SCALEFORM_SCRIPT_HUD_MOVIE_LOADED(HUD_COMPONENT_ID))
		{
			GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(HUD_COMPONENT_ID, "REMOVE");
			GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
		}
	}

	void OverrideAnimationSpeed(int speed = 1000)
	{
		Load();
		GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(HUD_COMPONENT_ID, "OVERRIDE_ANIMATION_SPEED");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(speed);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
	}

	void OverrideOnscreenDuration(int duration = 4000)
	{
		Load();
		GRAPHICS::BEGIN_SCALEFORM_SCRIPT_HUD_MOVIE_METHOD(HUD_COMPONENT_ID, "OVERRIDE_ONSCREEN_DURATION");
		GRAPHICS::SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(duration);
		GRAPHICS::END_SCALEFORM_MOVIE_METHOD();
	}
};
